general:
  startup_commands: []
  shutdown_commands: []
  config_reload_commands: ["wm-redraw"]

  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: false

    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "window_focus"

  hide_method: "cloak"
  show_all_in_taskbar: false

gaps:
  scale_with_dpi: true
  inner_gap: "12px"
  outer_gap:
    top: "20px"
    right: "20px"
    bottom: "20px"
    left: "20px"

window_effects:
  focused_window:
    border:
      enabled: false
      color: "#c6a0f6"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: "square"
    transparency:
      enabled: false
      opacity: "95%"

  other_windows:
    border:
      enabled: false
      color: "#6e738d"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: "square"
    transparency:
      enabled: false
      opacity: "0%"

window_behavior:
  # Allowed values: 'tiling', 'floating'.
  initial_state: "floating"

  state_defaults:
    floating:
      centered: true
      shown_on_top: false

    fullscreen:
      maximized: true
      shown_on_top: false

workspaces:
  - name: "1"
    display_name: ""
  - name: "2"
    display_name: ""
  - name: "3"
    display_name: ""
  - name: "4"
    display_name: ""
  - name: "5"
    display_name: ""
  - name: "6"
    display_name: "󰙴"
  - name: "7"
    display_name: "󰚾"
  - name: "8"
    display_name: "󰏰"
  - name: "9"
    display_name: ""

window_rules:
  - commands: ["ignore"]
    match:
      - window_process: { equals: "zebar" }

  - commands: ["set-tiling"]
    match:
      - window_process: { equals: "Code" }
      - window_process: { equals: "msedge" }
      - window_process: { equals: "chrome" }

keybindings:
  # Launch Windows Terminal.
  - commands: ["shell-exec wt"]
    bindings: ["alt+enter"]

  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["alt+h"]
  - commands: ["focus --direction right"]
    bindings: ["alt+l"]
  - commands: ["focus --direction up"]
    bindings: ["alt+k"]
  - commands: ["focus --direction down"]
    bindings: ["alt+j"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["alt+shift+h"]
  - commands: ["move --direction right"]
    bindings: ["alt+shift+l"]
  - commands: ["move --direction up"]
    bindings: ["alt+shift+k"]
  - commands: ["move --direction down"]
    bindings: ["alt+shift+j"]

  # Center the focused window on the screen.
  - commands: ["position --centered"]
    bindings: ["alt+c"]

  # Resize focused window by a percentage or pixel amount.
  - commands: ["resize --width -2%"]
    bindings: ["alt+u"]
  - commands: ["resize --width +2%"]
    bindings: ["alt+p"]
  - commands: ["resize --height +2%"]
    bindings: ["alt+o"]
  - commands: ["resize --height -2%"]
    bindings: ["alt+i"]

  # Disables window management and all other keybindings until alt+shift+p
  # is pressed again.
  - commands: ["wm-toggle-pause"]
    bindings: ["alt+shift+p"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+v"]

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ["wm-cycle-focus"]
    bindings: ["alt+space"]

  # Change the focused window to be floating.
  - commands: ["toggle-floating"]
    bindings: ["alt+f"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["alt+t"]

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["alt+shift+space"]

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["alt+m"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["alt+shift+q"]

  # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["alt+shift+e"]

  # Re-evaluate configuration file and Redraw all windows.
  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+r"]

  # Focus the next/previous workspace.
  - commands: ["focus --prev-workspace"]
    bindings: ["alt+oem_open_brackets"]
  - commands: ["focus --next-workspace"]
    bindings: ["alt+oem_close_brackets"]

  # Focus the next/previous active workspace.
  - commands: ["focus --prev-active-workspace"]
    bindings: ["alt+a"]
  - commands: ["focus --next-active-workspace"]
    bindings: ["alt+s"]

  # Focus the workspace that last had focus.
  - commands: ["focus --recent-workspace"]
    bindings: ["alt+d"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1"]
    bindings: ["alt+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["alt+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["alt+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["alt+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["alt+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["alt+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["alt+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["alt+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["alt+9"]

  # Move the focused window's parent workspace to a monitor in a given direction.
  # - commands: ["move-workspace --direction left"]
  #   bindings: ["alt+ctrl+h"]
  # - commands: ["move-workspace --direction right"]
  #   bindings: ["alt+ctrl+j"]
  # - commands: ["move-workspace --direction up"]
  #   bindings: ["alt+ctrl+k"]
  # - commands: ["move-workspace --direction down"]
  #   bindings: ["alt+ctrl+l"]

  # Move focused window to the next/previous workspace.
  - commands: ["move --prev-workspace", "focus --prev-workspace"]
    bindings: ["alt+shift+oem_open_brackets"]
  - commands: ["move --next-workspace", "focus --next-workspace"]
    bindings: ["alt+shift+oem_close_brackets"]

  # Move focused window to the next/previous active workspace.
  - commands: ["move --prev-active-workspace", "focus --prev-active-workspace"]
    bindings: ["alt+shift+a"]
  - commands: ["move --next-active-workspace", "focus --next-active-workspace"]
    bindings: ["alt+shift+s"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["alt+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["alt+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["alt+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["alt+shift+9"]
