watch_stylesheet: true
watch_config: true
debug: false
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 36
    widgets:
      left:
        - "home"
        - "clock"
        - "media"
        - "cava"
        # - "glazewm_tiling_direction"
        - "glazewm_binding_mode"
      center:
        - "glazewm_workspaces"
      right:
        - "systray"
        - "volume"
        - "wifi"
        - "apps"
        - "power_menu"
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\ue62a</span>"
      menu_labels:
        about: "\ue66A  About This PC"
        system: "\uF423  System Settings"
        task_manager: "\uf437  Task Manager"
        hibernate: "\uf28e  Hibernate"
        sleep: "\u23fe  Sleep"
        restart: "\uead2  Restart"
        shutdown: "\uf011  Shutdown"
        lock: "\uea75  Lock"
        logout: "\udb80\udf43  Logout"
      menu_list:
        - { title: "\uE617  Home", path: "~" }
        - { title: "\udb80\udd20  Download", path: "~\\Downloads" }
        - { title: "\udb80\ude1a  Documents", path: "~\\Documents" }
        - { title: "\uf03e  Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      border_color: "System"
      round_corners_type: "normal"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M}"
      label_alt: "{%a %d %b %H:%M}"
      callbacks:
        on_left: "toggle_label"
        on_right: "toggle_calendar"
      calendar:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        show_holidays: true
        show_week_numbers: true
        country_code: "VN"
        holiday_color: "#FF6464"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "{icon} {level}"
      # label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "󰁀" # Icon for muted
        - "󰀾" # Icon for 0-10% volume
        - "󰀿" # Icon for 11-30% volume
        - "󰀽" # Icon for 31-60% volume
        - "" # Icon for 61-100% volume
      callbacks:
        on_middle: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: ""
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 300 # Milisecond
      button_row: 3 # Number of buttons in row, min 1 max 5
      buttons:
        restart: ["R", "Restart"]
        shutdown: ["D", "Shut Down"]
        sleep: ["S", "Sleep"]
        lock: ["L", "Lock"]
        signout: ["O", "Sign out"]
        cancel: ["C", "Cancel"]
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      tooltip: false
      app_list:
        - { icon: "", launch: "quick_settings" }
        - { icon: "", launch: "notification_center" }
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      tooltip: false
      show_only_visible: false
      strict_filtering: false
      monitor_exclusive: false
      animation:
        enabled: true
      preview:
        enabled: true
        width: 450
        delay: 400
        padding: 12
      ignore_apps:
        processes: []
        titles: []
        classes: []
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: ""
      label_expanded: ""
      label_position: "right" # Can be "left" or "right"
      icon_size: 16 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: true
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: ""
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      max_field_size:
        label: 30
        label_alt: 30
      show_thumbnail: false
      controls_only: false
      controls_left: true
      controls_hide: false
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 90
        max_artist_size: 40
        show_source: true
        show_volume_slider: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
      scrolling_label:
        enabled: false
        update_interval_ms: 13
        style: "left" # can be "left", "right", "bounce", "bounce-ease"
        separator: "    |    "
        label_padding: 10
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
      enable_scroll_switching: false
      btn_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
      app_icons:
        enabled_populated: true
        enabled_active: true
        size: 16
        max_icons: 0
        hide_label: false
        hide_duplicates: true
        hide_floating: false
      animation: true
      populated_label: "{name} {display_name} "
      active_populated_label: "{name} {display_name} "
      active_empty_label: "{name}"
      focused_populated_label: "{name} {display_name} "
      focused_empty_label: "{name} {display_name}"
      empty_label: "{name}"
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      gradient: 1
      reverse: 0
      foreground: "#cba6f7"
      gradient_color_1: "#cba6f7"
      gradient_color_2: "#B4BEFE"
      bars_number: 8
      bar_spacing: 2
      bar_width: 5
      noise_reduction: 0.25
      sleep_timer: 2
      hide_empty: true
      container_padding:
        top: 0
        left: 4
        bottom: 0
        right: 4
  glazewm_binding_mode:
    type: "glazewm.binding_mode.GlazewmBindingModeWidget"
    options:
      hide_if_no_active: true
      label_if_no_active: "No binding mode active"
      default_icon: "\uf071"
      icons:
        none: ""
        resize: "◉"
      binding_modes_to_cycle_through: ["none", "resize"]
      callbacks:
        on_left: "disable_binding_mode"
        on_middle: "toggle_label"
        on_right: "disable_binding_mode"
  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "\udb81\udce1"
      vertical_label: "\udb81\udce2"
      btn_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_menu"
        on_middle: "exec cmd.exe /c start ms-settings:network"
        on_right: "toggle_label"
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span>{ip_addr}"
      ethernet_icon: "\ueba9"
      get_exact_wifi_strength: false # Optional. Will require location access permission if true.
      wifi_icons: [
          "\udb82\udd2e", # Icon for 0% strength
          "\udb82\udd1f", # Icon for 1-20% strength
          "\udb82\udd22", # Icon for 21-40% strength
          "\udb82\udd25", # Icon for 41-80% strength
          "\udb82\udd28", # Icon for 81-100% strength
        ]
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        wifi_icons_secured: ["\ue670", "\ue671", "\ue672", "\ue673"]
        wifi_icons_unsecured: ["\uec3c", "\uec3d", "\uec3e", "\uec3f"]
